deployment:
  replicas: 1
  sample:
    image:
      repository: ap6112560.azurecr.io/sample
      tag: f5ca26f5026e851a0c25052aea4e5e10a87edeef
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
